[project]
name = "taxi-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[duckdb,workspace]>=1.22.2",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.47",
]
